name: PlayerEffects
author: WolfLeader116
main: io.github.wolfleader116.playereffects.PlayerEffects
version: 1.0.7
description: PlayerEffects plugin.
depend: [WolfAPI]
commands:
  playereffects:
    description: Main PlayerEffects command.